name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Convert repository name to lowercase
      id: repo-name-lowercase
      run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: ./cdk/Dockerfile
        context: .
        push: true
        tags: ghcr.io/${{ steps.repo-name-lowercase.outputs.repo }}-cdk:latest
        build-args: |
          AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION=us-west-2
          AWS_DEFAULT_OUTPUT=json